# Generated by Django 4.2 on 2023-06-15 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=200)),
                ('state', models.CharField(default=None, max_length=200)),
                ('zipcode', models.IntegerField(default=None)),
                ('street_address', models.TextField(blank=True, default=None, null=True)),
                ('user_phone', models.IntegerField(blank=True, default=None, null=True)),
                ('default', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
