# Generated by Django 4.2 on 2023-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
