# Generated by Django 4.2 on 2023-06-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraddress_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
