# Generated by Django 4.2 on 2023-06-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
