# Generated by Django 4.2 on 2023-05-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
