# Generated by Django 4.2 on 2023-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_is_availabe_items_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.locations'),
        ),
    ]
