# Generated by Django 4.2 on 2023-05-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_items_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='location',
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_to',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispatched_from',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.locations'),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='zipcode',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
