# Generated by Django 4.2 on 2023-05-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_orders_location_orders_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
