# Generated by Django 4.2 on 2023-05-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_to',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dispatched_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.locations'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.IntegerField(default=None),
        ),
    ]
