# Generated by Django 4.2 on 2023-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_orders_city_alter_orders_delivered_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
