# Generated by Django 4.2 on 2023-05-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_orders_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
