# Generated by Django 4.2 on 2023-06-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_categories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.locations')),
            ],
            options={
                'verbose_name_plural': 'Warehouse',
            },
        ),
    ]
