# Generated by Django 4.2 on 2023-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='weight',
            field=models.FloatField(default=None),
        ),
    ]
