# Generated by Django 4.2 on 2023-06-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_items_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
