# Generated by Django 4.2 on 2023-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_items_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.ManyToManyField(to='inventory.locations'),
        ),
    ]
