# Generated by Django 4.2 on 2023-06-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_items_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.ManyToManyField(related_name='items', to='inventory.locations'),
        ),
    ]
