# Generated by Django 4.2 on 2023-06-02 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='location',
        ),
        migrations.AddField(
            model_name='items',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.locations'),
        ),
    ]
