# Generated by Django 4.2 on 2023-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
