# Generated by Django 4.2 on 2023-06-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_subcategories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
