# Generated by Django 4.2 on 2023-06-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_orders_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
