# Generated by Django 4.2 on 2023-06-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_items_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='items/% Y/% m/% d/'),
        ),
    ]
