# Generated by Django 4.2 on 2023-06-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_items_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='returned',
        ),
    ]
