# Generated by Django 4.2 on 2023-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_items_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='SKU_number',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
