# Generated by Django 4.2 on 2023-06-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_items_sku_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='ingredients',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
