# Generated by Django 4.2 on 2023-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_items_discription_items_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='street_address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
