# Generated by Django 4.2 on 2023-06-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
