# Generated by Django 4.2 on 2023-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_orders_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash_on_delivery', 'Cash On Delivery'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal')], default=None, max_length=20, null=True),
        ),
    ]
