# Generated by Django 4.2 on 2023-06-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_orders_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='zipcode',
        ),
    ]
