# Generated by Django 4.2 on 2023-06-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraddress_user'),
        ('inventory', '0034_remove_orders_city_remove_orders_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.useraddress'),
        ),
    ]
