# Generated by Django 4.2 on 2023-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_orders_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
