# Generated by Django 4.2 on 2023-06-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivered_to',
        ),
    ]
