# Generated by Django 4.2 on 2023-06-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_remove_orders_delivered_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash on delivery', 'Cash On Delivery'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal')], default=None, max_length=20, null=True),
        ),
    ]
