# Generated by Django 4.2 on 2023-06-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_orders_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='discription',
            new_name='description',
        ),
    ]
