# Generated by Django 4.2 on 2023-06-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_rename_discription_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancelled_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
