# Generated by Django 4.2 on 2023-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
