# Generated by Django 4.2 on 2023-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_orders_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
