# Generated by Django 4.2 on 2023-06-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_alter_orders_cancelled_on_alter_orders_delivered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='added_on',
        ),
    ]
