# Generated by Django 4.2 on 2023-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_remove_orders_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dispatched_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
