# Generated by Django 4.2 on 2023-06-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_ordertrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertrack',
            old_name='tracking_id',
            new_name='tracking_number',
        ),
    ]
