# Generated by Django 4.2 on 2023-06-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_rename_tracking_id_ordertrack_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertrack',
            name='dispatched_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.locations'),
        ),
    ]
