# Generated by Django 4.2 on 2023-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_ordertrack_dispatched_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertrack',
            name='expected_delivery_indays',
            field=models.IntegerField(default=0),
        ),
    ]
