# Generated by Django 4.2 on 2023-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_ordertrack_expected_delivery_indays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='SKU_number',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
