# Generated by Django 4.2 on 2023-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_alter_items_sku_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='location',
        ),
        migrations.AddField(
            model_name='items',
            name='locations',
            field=models.ManyToManyField(to='inventory.locations'),
        ),
    ]
